language: java
jdk:
  - oraclejdk8
env:
  - HADOOP_VERSION=2.7.6
  - HADOOP_VERSION=2.8.4
git:
  depth: 3

jobs:
  include:
    - stage: test
      name: "Build"
      script: "./gradlew build"
      install: true
    - name: "Unit tests"
      script: "./gradlew test --stacktrace --info -Ddyno.hadoop.bin.version=${HADOOP_VERSION}"

stages:
  - test

